import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

// import petstoreVersions from './docs/petstore_versioned/versions.json'

import { versionCrumb, versionSelector } from 'docusaurus-plugin-openapi-docs/lib/sidebars/utils'

import platformSidebar from './docs/platform_api/sidebar'
// import petstoreVersionSidebar from './docs/petstore_versioned/1.0.0/sidebar'
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const documentations: SidebarConfig = [
    {
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'doc',
        id: 'getting-started/introduction'
      },
      items: [
        'getting-started/introduction',
        'getting-started/key-features',
        'getting-started/quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Connectors',
      items: [
        {
          type: 'category',
          label: 'SCM Integrations',
          items: [
            'integrations/github',
            {
              type: 'category',
              label: 'GitLab',
              items: [
                'integrations/gitlab/index',
                'integrations/gitlab/self-hosted',
              ],
            },
            'integrations/bitbucket',
            'integrations/gitea',
          ],
        },
        {
          type: 'category',
          label: 'Cloud Deployment',
          items: [
            'integrations/aws',
            'integrations/azure',
            'integrations/gcp',
            'integrations/oci',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Plexicus Flow',
      items: [
        'applications/index', 
        'findings/index'
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      items: [
        'settings/change-password',
        'settings/two-factor-authentication',
      ],
    },
    {
      type: 'category',
      label: 'Organization',
      items: [
        'organization/client'
      ],
    },
  ]
const externalLinks: SidebarConfig = [
      {type: 'link', href: 'https://github.com/apps/plexicus', label: "Github Apps", customProps: {icon: 'carbon:logo-github'}}, 
    {type: 'link', href: 'https://github.com/marketplace/actions/plexicus-runner-action', label: "Github Action", customProps: {icon: 'material-icon-theme:github-actions-workflow'}}, 
    {type: 'link', href: 'https://blog.plexicus.ai', label: "Plexicus Blog", customProps: {icon: 'material-symbols:post-rounded'}}, 
]
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [...externalLinks, ...documentations],
    // multi versioned sidebar
  'platform-current': [
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v2.0.0`)
    },
    {
      type: 'category',
      label: 'Platform',
      link: {
        type: 'generated-index',
        title: 'Platform API (latest)',
        description:
          'This is a sample server Platform server. Generated by @docusaurus-plugin-openapi-docs plugin. Read more: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs',
        slug: '/category/platform_api'
      },
      items: platformSidebar
    }
  ],
};

export default sidebars;
